# The Final, Working Docker Compose File
services:
  kafka:
    image: confluentinc/cp-kafka:7.4.10
    container_name: kafka
    # We create and use a custom network for better isolation
    networks:
      - day2_default
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'ouA7o6IARKKXrmWvCkQNbg'

      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

# Define the custom network
networks:
  day2_default:
    driver: bridge